export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FETCHED = 'USER_FETCHED';
export const GAMES_FETCHED = 'GAMES_FETCHED';
export const USER_IS_LOGIN = 'USER_IS_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';